---
- name: Install language pack
  apt: name=language-pack-{{ item[0:2] }} state=present
  with_items:
  - "{{ locale_lang }}"

- name: Create locale
  locale_gen: name={{ locale_lang }} state=present

- name: Set locale
  template:
    src: default.j2
    dest: /etc/default/locale

- name: Validate timezone variable
  stat: path=/usr/share/zoneinfo/{{ default_timezone }}
  register: timezone_path
  changed_when: false

- name: Explain timezone error
  fail: msg="{{ default_timezone }} is not valid. For a list of valid timezones, check https://php.net/manual/en/timezones.php"
  when: not timezone_path.stat.exists

- name: Get current timezone
  command: cat /etc/timezone
  register: current_timezone
  changed_when: false

- name: Set timezone
  command: timedatectl set-timezone {{ default_timezone }}
  when: current_timezone.stdout != default_timezone
