---
- name: Install 'language-pack-{{ locale[0:2] }}'
  package:
    name: language-pack-{{ item[0:2] }}
    state: present
  with_items:
    - "{{ locale }}"
  when: ansible_distribution == 'Ubuntu'

- name: Generate locale for '{{ locale }}'
  locale_gen:
    name: "{{ locale }}"
    state: present

- name: Check localectl status
  command: localectl status
  register: localectl_current
  changed_when: false

- name: Get current system settings
  set_fact:
    keymap_current: "{{ localectl_current.stdout | regex_search('Keymap: ([^\n]+)', '\\1') | first }}"
    locale_current: "{{ localectl_current.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"
    language_current: "{{ localectl_current.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale], true) | first }}"

- name: Set locale to '{{ locale }}', language to '{{ language }}'
  command: localectl set-locale LANG={{ locale }} LANGUAGE={{ language }}
  when: locale_current != locale or language_current != language

- name: Set keyboard layout
  command: localectl set-keymap --no-convert {{ keymap }}
  when: keymap_current != keymap

- name: Check timezone
  command: "timedatectl show"
  register: timedatectl_current
  changed_when: false

- name: Set timezone
  command: timedatectl set-timezone {{ timezone }}
  changed_when: timezone not in timedatectl_current.stdout
