---
- name: Install language pack
  apt: name=language-pack-{{ item[0:2] }} state=present
  with_items:
  - "{{ locale_lang }}"

- name: Create locale
  locale_gen: name={{ locale_lang }} state=present

- name: Set locale
  template:
    src: default.j2
    dest: /etc/default/locale
