---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - "default.yml"

- name: Install language pack
  package:
    name: language-pack-{{ item[0:2] }}
    state: present
  with_items:
    - "{{ locale_lang }}"
  when: ansible_distribution == 'Ubuntu'

- name: Generate locale
  locale_gen:
    name: "{{ locale_lang }}"
    state: present

- name: Set locale
  template:
    src: default.j2
    dest: "{{ locale_file }}"

- name: Check current timezone
  command: "timedatectl show"
  register: timedatectl_current
  changed_when: false

- name: Set timezone
  command: timedatectl set-timezone {{ timezone }}
  changed_when: timezone not in timedatectl_current.stdout
