---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - "default.yml"

- name: Install language pack
  package:
    name: language-pack-{{ item[0:2] }}
    state: present
  with_items:
    - "{{ locale_lang }}"
  when: ansible_distribution == 'Ubuntu'

- name: Generate locale
  locale_gen:
    name: "{{ locale_lang }}"
    state: present

- name: Set locale
  template:
    src: default.j2
    dest: "{{ locale_file }}"

- name: Checking timezone variable
  stat:
    path: "/usr/share/zoneinfo/{{ timezone }}"
  register: timezone_path
  changed_when: false

- name: Validate timezone variable
  fail:
    msg: "{{ timezone }} is not valid. For valid timezones, check https://en.wikipedia.org/wiki/List_of_tz_database_time_zones"
  when: not timezone_path.stat.exists

- name: Set timezone
  command: timedatectl set-timezone {{ timezone }}
  when: current_timezone.stdout != timezone
